In [2]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [3]:
data = pd.read_csv('iris.data.csv')
# Printing the dataset shape
print ("Dataset Length: ", len(data))
print ("Dataset Shape: ", data.shape)
# Printing the dataset obseravtions
print ("Dataset:\n ",data.head())

Dataset Length:  150
Dataset Shape:  (150, 5)
Dataset:
     sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa


In [20]:
data['class'],_ = pd.factorize(data['class'])
## data.info()
# Separating the target variable
X = data.iloc[:, 0:4].values
y = data.iloc[:, 4].values
# Splitting the dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state=0)


In [18]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)
# making predictions on the testing set
y_pred = gnb.predict(X_test)

In [19]:
print("Results Using Gaussian Naive Bayes Classifier\n\n")
print("Confusion Matrix:\n ", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test,y_pred)*100)
print("Report :\n ", classification_report(y_test, y_pred))

Results Using Gaussian Naive Bayes Classifier


Confusion Matrix:
  [[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
Accuracy :  100.0
Report :
                precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00         9

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

